name: bamboo
description: A posture tracking application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  google_fonts: ^0.3.5
  flutter_sequence_animation: ^3.0.1
  rubber: ^0.4.0
  animated_text_kit: ^2.0.0
  firebase_core: ^0.4.3+2
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.13.0+1
  modal_progress_hud: ^0.1.3
  expandable_card: ^0.0.3+1
  flutter_3d_obj: ^0.0.6
  syncfusion_flutter_charts: ^17.4.43

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/
